name: MagiskPolicy Build for APatch

on:
  push:
    branches: [master]
    paths:
      - "app/**"
      - "native/**"
      - "buildSrc/**"
      - "build.py"
      - "gradle.properties"
      - ".github/workflows/build.yml"
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build APatch required artifacts
    runs-on: ubuntu-latest
    env:
      SCCACHE_DIRECT: false
    strategy:
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Build magiskpolicy
        run: ./build.py -vr binary magiskpolicy

      - name: Build resetprop
        run: ./build.py -vr binary resetprop

      - name: Stop gradle daemon
        run: ./gradlew --stop

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: native/out/arm64-v8a
          compression-level: 9
